---
- name: Installation de Apache http serveur
  hosts: serveur2:serveur3
  tasks:
    - name: Intallation de la dernier version de Apache
      yum:
        name: httpd
        state: latest
    - name: s'assurer que httpd tourne
      service:
        name: httpd
        state: started
    - name: ouvrir le port 80/TCP
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: redemarrer le service firewalld
      service:
        name: firewalld
        state: restarted
